### ISSUE TITLE
Please respect paths convention

### ISSUE THREAD

**Issue by posophe** [sk1project/sk1-tk#1]
Hello,

Actually, sk1 want's to install his files into irregular paths. Icons should be installed in /usr/share/icons/,
the python libraries into $sitelib, the tcl libraries into $libdir/tcl.

Actually, sk1-tk tries to install everything in /usr/lib, making it impossible to package.

Regards.
Benjamin

**Comment by sk1project** [comment]
Actually sk1-tk is deprecated project. sk1-wx is successor. 

Concerning installation rules, sk1-wx uses similar scheme because this simplifies MSW and OSX versions. Such behavior doesn't break packaging process. We have published some deb packages for Release Candidate 1.

**Comment by posophe** [comment]
Ok but it does break the packaging as far as it doesn't repsect the FHS standards.
